#!/bin/bash
set -euo pipefail

log() {
  echo "[$(date -u +'%Y-%m-%dT%H:%M:%SZ')] $*"
}

log "VPN tunnel up (dev=${dev:-?} local=${ifconfig_local:-?})"

# Fixed inside container — host publish uses PROXY_HTTP_PORT / PROXY_SOCKS_PORT in compose
HTTP_PROXY_PORT=8888
SOCKS_PROXY_PORT=1080

# Push VPN DNS into resolv.conf when provided by OpenVPN
if [[ -n "${foreign_option_1:-}" ]]; then
  {
    echo "# generated by proxy2vpn tunnelUp"
    idx=1
    while true; do
      var="foreign_option_${idx}"
      value="${!var:-}"
      [[ -z "$value" ]] && break
      if [[ "$value" == dhcp-option\ DNS\ * ]]; then
        echo "nameserver ${value##* }"
      fi
      idx=$((idx + 1))
    done
  } > /etc/resolv.conf
fi

# Kill switch: only allow outbound via tun (+ established + local nets)
iptables -F OUTPUT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -o "${dev:-tun0}" -j ACCEPT

if [[ -n "${LOCAL_NETWORK:-}" ]]; then
  for net in ${LOCAL_NETWORK//,/ }; do
    iptables -A OUTPUT -d "${net}" -j ACCEPT
  done
fi

# Keep VPN endpoint reachable on eth0 while tunnel flaps
if [[ -n "${trusted_ip:-}" ]]; then
  iptables -A OUTPUT -d "${trusted_ip}" -j ACCEPT
fi

iptables -A OUTPUT -j DROP
log "Kill switch active on OUTPUT"

# HTTP proxy
TINYPROXY_CONF="/tmp/tinyproxy.conf"
cp /etc/tinyproxy/tinyproxy.conf.tmpl "$TINYPROXY_CONF"
sed -i "s/__HTTP_PROXY_PORT__/${HTTP_PROXY_PORT}/g" "$TINYPROXY_CONF"

if [[ -n "${PROXY_USER:-}" && -n "${PROXY_PASSWORD:-}" ]]; then
  echo "BasicAuth ${PROXY_USER} ${PROXY_PASSWORD}" >> "$TINYPROXY_CONF"
fi

pkill tinyproxy 2>/dev/null || true
mkdir -p /var/log/tinyproxy
chown -R tinyproxy:tinyproxy /var/log/tinyproxy
tinyproxy -c "$TINYPROXY_CONF"
log "tinyproxy listening on :${HTTP_PROXY_PORT}"

# SOCKS5 proxy
pkill microsocks 2>/dev/null || true
MICROSOCKS_ARGS=(-i 0.0.0.0 -p "${SOCKS_PROXY_PORT}")
if [[ -n "${PROXY_USER:-}" && -n "${PROXY_PASSWORD:-}" ]]; then
  MICROSOCKS_ARGS+=(-u "${PROXY_USER}" -P "${PROXY_PASSWORD}")
fi
microsocks "${MICROSOCKS_ARGS[@]}" &
echo $! > /tmp/microsocks.pid
log "microsocks listening on :${SOCKS_PROXY_PORT}"

# Persist status for healthcheck
{
  echo "up"
  date -u +'%Y-%m-%dT%H:%M:%SZ'
  echo "${ifconfig_local:-unknown}"
} > /tmp/vpn-status

log "Proxies ready — HTTP :${HTTP_PROXY_PORT}  SOCKS5 :${SOCKS_PROXY_PORT}"

PUBLIC_IP=""
for _ in 1 2 3 4 5; do
  PUBLIC_IP="$(curl -fsS --max-time 8 https://ifconfig.me/ip 2>/dev/null || true)"
  if [[ -n "${PUBLIC_IP}" ]]; then
    break
  fi
  sleep 2
done

if [[ -n "${PUBLIC_IP}" ]]; then
  log "Public IP (via VPN): ${PUBLIC_IP}"
  echo "${PUBLIC_IP}" >> /tmp/vpn-status
else
  log "WARNING: could not resolve public IP via VPN yet"
fi

# ProtonVPN NAT-PMP when OpenVPN username contains +pmp
OVPN_USER="$(head -n1 /config/openvpn-credentials.txt 2>/dev/null || true)"
if [[ "${OVPN_USER}" == *"+pmp"* ]]; then
  pkill -f '/etc/openvpn/port-forward.sh' 2>/dev/null || true
  # Background; script kills PID 1 if PF fails
  /etc/openvpn/port-forward.sh &
  echo $! > /tmp/port-forward.pid
fi
